# Generated by Django 2.0.6 on 2018-09-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(blank=True, max_length=150, null=True, verbose_name='Logradouro')),
                ('bairro', models.CharField(blank=True, max_length=150, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=150, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=150, null=True, verbose_name='Estado')),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='Número')),
                ('principal', models.BooleanField(default=False, verbose_name='Endereço principal')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
    ]
